#spring:
#profiles:
#active:
server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost/questionmarks
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

#        logging:
#        path: /var/logs/
#        file: TacoCloud.log
#        level:
#        root: WARN
#        org:
#        springframework:
#        security: DEBUG


#logging:
#level:
#tacos: DEBUG
#---
#spring:
#profiles: prod
#datasource:
#url: jdbc:mysql://localhost/tacocloud
#username: tacouser
#password: tacopassword
#logging:
#level:
#tacos: WARN